apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : "Test@123"
        - name: MYSQL_DATABASE
          value : "bankappdb"  
        ports:
        - containerPort: 3306
          name: mysql
        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql


 -----

 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  selector:
    matchLabels:
      app: bankapp
  
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      -name : bankapp
       image : sameera7268/bankapp:latest
      
      env:
        - name: spring_datavase_url
          value : jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: spring_database_username
          value : root  
        - name: spring_database_password
          value : Test@123  
      ports:
        - containerPort: 8080  


 -----
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp             
